version: '3.9'

services:
  hotelmanagementservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDb: mongodb://mongodb:27017
      RabbitMQ__HostName: rabbitmq
      ASPNETCORE_HTTP_PORTS: "5000"
      ASPNETCORE_HTTPS_PORTS: "5050"
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5000:5000"
      - "5050:5050"

  reportservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDb: mongodb://mongodb:27017
      RabbitMQ__HostName: rabbitmq
      ASPNETCORE_HTTP_PORTS: "5001"
      ASPNETCORE_HTTPS_PORTS: "5051"
      ASPNETCORE_URLS: http://+:5001
    ports:
      - "5001:5001"
      - "5051:5051"
